baseURL = "https://quo.wtf"
languageCode = "es-MX"
defaultContentLanguage = "en"
title = "quo.wtf"
theme = "diurnus"
removePathAccents = true

[permalinks]
  posts = '/:year/:month/:day/:title'

[taxonomies]
  tag = "tags"
  category = "categories"
  language = "languages"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  homeSubtitle = "quid pro quo"

[[params.social]]
  name = "instagram"
  url = "https://instagram.com/lunareswww"

[[params.social]]
  name = "github"
  url = "https://github.com/quowtf"

[[params.social]]
  name = "AltKeyCLub"
  url = "https://altkey.club"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

[markup.goldmark.renderer]
  unsafe= true
