baseURL = "https://quo.wtf"
languageCode = "es-MX"
defaultContentLanguage = "en"
title = "quo.wtf"
theme = "diurnus"

[permalinks]
  posts = '/:year/:month/:day/:title'

[taxonomies]
  tag = "tags"
  category = "categories"
  language = "languages"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  homeSubtitle = "quid pro quo"
  plausibleDomain = "quo.wtf"
  plausibleSrc = "/js/script.js"

[[params.social]]
  name = "AltKeyCLub"
  url = "https://altkey.club"

[[params.social]]
  name = "instagram"
  url = "https://instagram.com/roberto.lunas"

[[params.social]]
  name = "github"
  url = "https://github.com/quowtf"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "MeNow"
    url = "menow/"
    weight = 20

[markup.goldmark.renderer]
  unsafe= true
