baseURL = "https://quo.wtf"
languageCode = "es-MX"
defaultContentLanguage = "en"
title = "quo.wtf"
theme = "diurnus"

[author]
  name = "RE"

[taxonomies]
  tag = "tags"
  category = "categories"
  language = "languages"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  homeSubtitle = "quid pro quo"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/quowtf"

[[params.social]]
  name = "vsco"
  url = "https://vsco.co/quowtf"

[[params.social]]
  name = "github"
  url = "https://github.com/quowtf"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "MeNow"
    url = "menow/"
    weight = 20

[markup.goldmark.renderer]
  unsafe= true
